# Generated by Django 4.2.9 on 2024-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ref_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=15)),
                ('thumbnail', models.TextField()),
                ('images', models.JSONField()),
                ('source', models.URLField()),
                ('details', models.JSONField()),
            ],
        ),
    ]
