# Generated by Django 4.2.9 on 2024-01-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ref_no',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
